project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Student Performance"
  author:
    - Yueer Liu(yl5766)
    - Ziying Song (zs2698)
  repo-url: https://github.com/ssong423/studentPerformance
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true